# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 524)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitleSavedModelPath = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitleSavedModelPath.sizePolicy().hasHeightForWidth())
        self.labelTitleSavedModelPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleSavedModelPath.setFont(font)
        self.labelTitleSavedModelPath.setObjectName("labelTitleSavedModelPath")
        self.verticalLayout.addWidget(self.labelTitleSavedModelPath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSavedModelPath = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSavedModelPath.sizePolicy().hasHeightForWidth())
        self.labelSavedModelPath.setSizePolicy(sizePolicy)
        self.labelSavedModelPath.setObjectName("labelSavedModelPath")
        self.horizontalLayout.addWidget(self.labelSavedModelPath)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.btnOpenSavedModelPath = QtWidgets.QPushButton(self.centralWidget)
        self.btnOpenSavedModelPath.setObjectName("btnOpenSavedModelPath")
        self.horizontalLayout.addWidget(self.btnOpenSavedModelPath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.labelTitleLabelMapPath = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitleLabelMapPath.sizePolicy().hasHeightForWidth())
        self.labelTitleLabelMapPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleLabelMapPath.setFont(font)
        self.labelTitleLabelMapPath.setObjectName("labelTitleLabelMapPath")
        self.verticalLayout.addWidget(self.labelTitleLabelMapPath)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelLabelMapPath = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLabelMapPath.sizePolicy().hasHeightForWidth())
        self.labelLabelMapPath.setSizePolicy(sizePolicy)
        self.labelLabelMapPath.setObjectName("labelLabelMapPath")
        self.horizontalLayout_6.addWidget(self.labelLabelMapPath)
        self.line_9 = QtWidgets.QFrame(self.centralWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_6.addWidget(self.line_9)
        self.btnOpenLabelMapPath = QtWidgets.QPushButton(self.centralWidget)
        self.btnOpenLabelMapPath.setObjectName("btnOpenLabelMapPath")
        self.horizontalLayout_6.addWidget(self.btnOpenLabelMapPath)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_8 = QtWidgets.QFrame(self.centralWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.labelTitleTestDataPath = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitleTestDataPath.sizePolicy().hasHeightForWidth())
        self.labelTitleTestDataPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleTestDataPath.setFont(font)
        self.labelTitleTestDataPath.setObjectName("labelTitleTestDataPath")
        self.verticalLayout.addWidget(self.labelTitleTestDataPath)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTestDataPath = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTestDataPath.sizePolicy().hasHeightForWidth())
        self.labelTestDataPath.setSizePolicy(sizePolicy)
        self.labelTestDataPath.setObjectName("labelTestDataPath")
        self.horizontalLayout_2.addWidget(self.labelTestDataPath)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.btnOpenTestDataPath = QtWidgets.QPushButton(self.centralWidget)
        self.btnOpenTestDataPath.setObjectName("btnOpenTestDataPath")
        self.horizontalLayout_2.addWidget(self.btnOpenTestDataPath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnStartStop = QtWidgets.QPushButton(self.centralWidget)
        self.btnStartStop.setObjectName("btnStartStop")
        self.horizontalLayout_4.addWidget(self.btnStartStop)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.btnShowResult = QtWidgets.QPushButton(self.centralWidget)
        self.btnShowResult.setObjectName("btnShowResult")
        self.horizontalLayout_4.addWidget(self.btnShowResult)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.labelStatus = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(105, 0))
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.horizontalLayout_4.addWidget(self.labelStatus)
        self.line_10 = QtWidgets.QFrame(self.centralWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_4.addWidget(self.line_10)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.sliderThreshold = QtWidgets.QSlider(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderThreshold.sizePolicy().hasHeightForWidth())
        self.sliderThreshold.setSizePolicy(sizePolicy)
        self.sliderThreshold.setMinimumSize(QtCore.QSize(120, 0))
        self.sliderThreshold.setMinimum(1)
        self.sliderThreshold.setMaximum(99)
        self.sliderThreshold.setSingleStep(1)
        self.sliderThreshold.setPageStep(5)
        self.sliderThreshold.setProperty("value", 50)
        self.sliderThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.sliderThreshold.setInvertedAppearance(False)
        self.sliderThreshold.setInvertedControls(False)
        self.sliderThreshold.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderThreshold.setObjectName("sliderThreshold")
        self.horizontalLayout_4.addWidget(self.sliderThreshold)
        self.labelThresholdValue = QtWidgets.QLabel(self.centralWidget)
        self.labelThresholdValue.setMinimumSize(QtCore.QSize(30, 0))
        self.labelThresholdValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThresholdValue.setObjectName("labelThresholdValue")
        self.horizontalLayout_4.addWidget(self.labelThresholdValue)
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_4.addWidget(self.line_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.texteditResult = QtWidgets.QTextEdit(self.centralWidget)
        self.texteditResult.setObjectName("texteditResult")
        self.horizontalLayout_5.addWidget(self.texteditResult)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuTest = QtWidgets.QMenu(self.menuBar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_Saved_Model_Path = QtWidgets.QAction(MainWindow)
        self.actionOpen_Saved_Model_Path.setObjectName("actionOpen_Saved_Model_Path")
        self.actionOpen_Labelmap_Path = QtWidgets.QAction(MainWindow)
        self.actionOpen_Labelmap_Path.setObjectName("actionOpen_Labelmap_Path")
        self.actionOpen_Testdata_Path = QtWidgets.QAction(MainWindow)
        self.actionOpen_Testdata_Path.setObjectName("actionOpen_Testdata_Path")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionResult = QtWidgets.QAction(MainWindow)
        self.actionResult.setObjectName("actionResult")
        self.menuFile.addAction(self.actionOpen_Saved_Model_Path)
        self.menuFile.addAction(self.actionOpen_Labelmap_Path)
        self.menuFile.addAction(self.actionOpen_Testdata_Path)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTest.addAction(self.actionRun)
        self.menuTest.addAction(self.actionResult)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TestSuite"))
        self.labelTitleSavedModelPath.setText(_translate("MainWindow", "Saved Model Path"))
        self.labelSavedModelPath.setText(_translate("MainWindow", "None"))
        self.btnOpenSavedModelPath.setText(_translate("MainWindow", "Open"))
        self.labelTitleLabelMapPath.setText(_translate("MainWindow", "Label Map File Path"))
        self.labelLabelMapPath.setText(_translate("MainWindow", "None"))
        self.btnOpenLabelMapPath.setText(_translate("MainWindow", "Open"))
        self.labelTitleTestDataPath.setText(_translate("MainWindow", "Test Data Path(Use Directory Based Class)"))
        self.labelTestDataPath.setText(_translate("MainWindow", "None"))
        self.btnOpenTestDataPath.setText(_translate("MainWindow", "Open"))
        self.btnStartStop.setText(_translate("MainWindow", "Start"))
        self.btnShowResult.setText(_translate("MainWindow", "Result"))
        self.labelStatus.setText(_translate("MainWindow", "Status"))
        self.labelThresholdValue.setText(_translate("MainWindow", "50%"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTest.setTitle(_translate("MainWindow", "Test"))
        self.actionOpen_Saved_Model_Path.setText(_translate("MainWindow", "Open Saved Model Path"))
        self.actionOpen_Labelmap_Path.setText(_translate("MainWindow", "Open Label Map File Path"))
        self.actionOpen_Testdata_Path.setText(_translate("MainWindow", "Open Test Data Path"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionResult.setText(_translate("MainWindow", "Result"))

